 $(document).ready(function(){
  $(".owl-carousel").owlCarousel({
    loop:true,
    margin:250,
    autoplay:true,
    smartSpeed:1000,
    autoplayTimeout:3000,
    responsive:{ //Адаптивность. Кол-во выводимых элементов при определенной ширине.
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:3
                }
            }
  });
});